[package]
name = "prost-build"
# NB: When modifying, also modify html_root_url in lib.rs
version = "0.5.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "Apache-2.0"
repository = "https://github.com/danburkert/prost"
documentation = "https://docs.rs/prost-build"
readme = "README.md"
description = "A Protocol Buffers implementation for the Rust Language."
edition = "2018"

[dependencies]
bytes = { git = "https://github.com/tokio-rs/bytes.git", default-features = false }
heck = "0.3"
itertools = "0.8"
log = "0.4"
multimap = { version = "0.4", default-features = false }
petgraph = { version = "0.4", default-features = false }
prost = { version = "0.5.0", path = "..", default-features = false }
prost-types = { version = "0.5.0", path = "../prost-types", default-features = false }
tempfile = "3"

[build-dependencies]
which = "2"

[dev-dependencies]
env_logger = { version = "0.6", default-features = false }


[features]
default = ["std"]
std = ["bytes/std", "prost/std", "prost-types/std"]
