[package]
name = "fuzz-target-proto3"
version = "0.1.0"
authors = ["Prost developers"]
edition = "2018"

[dependencies]
afl = "0.4"
protobuf = { path = "../../protobuf/" }
tests = { path = "../../tests/" }
